name: wf-prueba

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-23.10.1
    steps:
      - name: Echo the message
        run: |
          echo "Hola mundo!"
      - name: Dime la fecha
        run: date
      - run: ls -l